# Generated by Django 4.1.3 on 2023-01-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('field1', models.CharField(blank=True, max_length=20, null=True)),
                ('field2', models.CharField(blank=True, max_length=20, null=True)),
                ('field3', models.CharField(blank=True, max_length=20, null=True)),
                ('field4', models.CharField(blank=True, max_length=20, null=True)),
                ('field5', models.CharField(blank=True, max_length=20, null=True)),
                ('type_field1', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field2', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field3', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field4', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field5', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('api_key', models.CharField(blank=True, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=10, null=True)),
                ('field2', models.CharField(blank=True, max_length=10, null=True)),
                ('field3', models.CharField(blank=True, max_length=10, null=True)),
                ('field4', models.CharField(blank=True, max_length=10, null=True)),
                ('field5', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
