# Generated by Django 4.1.3 on 2023-01-27 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('device_type', models.CharField(max_length=60)),
                ('field1', models.CharField(blank=True, max_length=20, null=True)),
                ('field2', models.CharField(blank=True, max_length=20, null=True)),
                ('field3', models.CharField(blank=True, max_length=20, null=True)),
                ('field4', models.CharField(blank=True, max_length=20, null=True)),
                ('field5', models.CharField(blank=True, max_length=20, null=True)),
                ('type_field1', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field2', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field3', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field4', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('type_field5', models.CharField(choices=[('DF', 'DataField'), ('HS', 'HumiditySensor'), ('LS', 'LightSensor'), ('TS', 'TemperatureSensor'), ('RY', 'RELAY')], default='DF', max_length=2)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('api_key', models.CharField(blank=True, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=10, null=True)),
                ('field2', models.CharField(blank=True, max_length=10, null=True)),
                ('field3', models.CharField(blank=True, max_length=10, null=True)),
                ('field4', models.CharField(blank=True, max_length=10, null=True)),
                ('field5', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.device')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('field', models.IntegerField()),
                ('condition_value', models.IntegerField()),
                ('message', models.TextField(max_length=200)),
                ('frequency', models.BooleanField(default=False)),
                ('activition', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.device')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
