# Generated by Django 4.1.3 on 2023-01-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_data_field1_alter_data_field2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='field1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
