# Generated by Django 4.1.3 on 2023-01-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_data_field1_alter_data_field2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('i', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('linechart', 'Line Chart'), ('temperature', 'Temperature Chart')], max_length=20)),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('maxH', models.IntegerField()),
                ('minH', models.IntegerField()),
                ('maxW', models.IntegerField()),
                ('minW', models.IntegerField()),
                ('moved', models.BooleanField(default=False)),
                ('static', models.BooleanField(default=False)),
                ('isResizable', models.BooleanField(default=False)),
                ('datafield', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.data')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.device')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
