# Generated by Django 4.1.3 on 2023-01-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='field',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='widget',
            name='datafield',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafield_attribute', to='base.data'),
        ),
    ]
