# Generated by Django 4.1.3 on 2023-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_alert_field_alter_widget_datafield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='field',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='widget',
            name='datafield',
            field=models.CharField(max_length=20),
        ),
    ]
