# Generated by Django 4.1.3 on 2023-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_alert_field_alter_widget_datafield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='maxH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='maxW',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='minH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='minW',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
