# Generated by Django 4.1.3 on 2023-01-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('linechart', 'Line Chart'), ('gauge', 'Gauge Chart'), ('switch', 'Switch Control'), ('indicator', 'Indicator Chart'), ('percentage', 'Percentage Chart')], max_length=20),
        ),
    ]
