# Generated by Django 4.1.3 on 2023-01-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_widget_x_alter_widget_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
