# Generated by Django 4.1.3 on 2023-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_alert_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='field',
            field=models.CharField(max_length=20),
        ),
    ]
