# Generated by Django 4.1.3 on 2023-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_widget_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='widget',
            name='w',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
