# Generated by Django 4.1.3 on 2023-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_widget_h_alter_widget_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('linechart', 'Line Chart'), ('gauge', 'Gauge Chart'), ('switch', 'Switch Control'), ('indicator', 'Indicator Chart'), ('percentage', 'Percentage Chart')], default='linechart', max_length=20),
        ),
        migrations.AlterField(
            model_name='widget',
            name='w',
            field=models.IntegerField(null=True),
        ),
    ]
